In [73]:
#############关于view，reshape，resize_
import torch
import torch.nn as nn
rr = torch.arange(1,16)
print(rr.shape)                              #torch.Size([15])         

torch.Size([15])


In [67]:
###############view函数只适用于形状相同的变化,变化前后共享数据，但不共享内存
rr1 = rr.view(5,3)
print(rr1.shape)                                                                            #torch.Size([5, 3])
############不共享内存
print(id(rr1) == id(rr))                                                                    #False
###########共享数据,理解为单个scalar从同一片内存区去取
print(id(rr1[0,0])==id(rr[0]))                                                              #True
print(id(rr1.untyped_storage()) == id(rr.untyped_storage()))                                #True
print(id(rr1.untyped_storage()[0]) == id(rr.untyped_storage()[0]))                          #True
# rr2 = rr.view(5,2)#########形状不同会报错

torch.Size([5, 3])
False
True
True
True
tensor(True)


In [68]:
rr3 = rr.reshape(5,3)
print(id(rr1) == id(rr3) == id(rr))
#########因为rr为连续存储的数据，所以这儿内存地址一致
print(id(rr1.untyped_storage()) == id(rr3.untyped_storage()) == id(rr.untyped_storage()))

False
True


In [69]:
###################共享数据的特点，基础元素变化都变化了
rr[0] = 3
print(rr1)
print(rr3)
print(rr)

tensor([[ 3,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
tensor([[ 3,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
tensor([ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])


In [72]:
#######矩阵转置就会让内存变得不连续，因此无法使用view进行形状变换
#t1.T.view(3,10)
###################reshape可以使用，但发生了拷贝,此时数据区地址不一致了
t2 = t1.T.reshape(3,10)
print(id(t1.untyped_storage()) == id(t2.untyped_storage()))

False


In [55]:
################resize
m5 = torch.randn(5,6)
m3 = m5.resize_(3,9)
m4 = m5.resize_(3,10)
print(m3)
print(id(m5.untyped_storage()) == id(m3.untyped_storage()))
print(id(m5.untyped_storage()) == id(m4.untyped_storage()))

##############转置会让打乱连续的数据存储，非连续存储也能调用
m5.T.resize_(6,6)

tensor([[ 8.1499e-01,  4.8655e-01, -1.8174e+00,  2.5629e-03,  5.5115e-01,
          1.0890e-01,  2.2603e+00, -7.9960e-01, -4.0538e-01, -6.8531e-01],
        [-5.3938e-01,  1.0152e-01, -8.1363e-01, -6.6595e-02,  1.0276e+00,
         -1.7276e+00,  5.8043e-01,  1.8335e+00, -1.5041e+00, -9.7158e-01],
        [ 9.9915e-01,  5.4939e-01, -3.4991e-01, -2.9098e+00,  1.4687e+00,
         -4.6404e-01, -4.0539e-01,  1.5796e+00,  2.0464e-01,  1.2823e-01]])
True
True


tensor([[ 8.1499e-01,  4.8655e-01, -1.8174e+00,  2.5629e-03,  5.5115e-01,
          1.0890e-01],
        [ 2.2603e+00, -7.9960e-01, -4.0538e-01, -6.8531e-01, -5.3938e-01,
          1.0152e-01],
        [-8.1363e-01, -6.6595e-02,  1.0276e+00, -1.7276e+00,  5.8043e-01,
          1.8335e+00],
        [-1.5041e+00, -9.7158e-01,  9.9915e-01,  5.4939e-01, -3.4991e-01,
         -2.9098e+00],
        [ 1.4687e+00, -4.6404e-01, -4.0539e-01,  1.5796e+00,  2.0464e-01,
          1.2823e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00]])